version: '3.8'
services:
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=development
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_MULTIPLE_DATABASES="shit_dev,shit_test"
    ports:
      - 5444:5432
    volumes:
      - ./scripts/entrypoints:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
